using System;
using System.Collections.Generic;
using System.Linq;
using System.Data;
namespace HT_Stock.BOJ
{
	public class clsBalanceinventaire
	{
		#region VARIABLES LOCALES

		private string _AG_CODEAGENCE = "";
		private string _EN_CODEENTREPOT = "";
		private string _EX_EXERCICE = "";
		private string _PL_CODENUMCOMPTE = "";
		private string _MV_LIBELLEOPERATION = "";
		private double _PL_MONTANTPERIODEPRECEDENTDEBIT = 0;
		private double _PL_MONTANTPERIODEPRECEDENTCREDIT = 0;
		private double _PL_MONTANTPERIODEDEBITENCOURS = 0;
		private double _PL_MONTANTPERIODECREDITENCOURS = 0;
		private double _PL_MONTANTSOLDEFINALDEBIT = 0;
		private double _PL_MONTANTSOLDEFINALCREDIT = 0;
		private double _PL_MONTANTPERIODEPRECEDENTDEBITTOTAL = 0;
		private double _PL_MONTANTPERIODEPRECEDENTCREDITTOTAL = 0;
		private double _PL_MONTANTPERIODEDEBITENCOURSTOTAL = 0;
		private double _PL_MONTANTPERIODECREDITENCOURSTOTAL = 0;
		private double _PL_MONTANTSOLDEFINALDEBITTOTAL = 0;
		private double _PL_MONTANTSOLDEFINALCREDITTOTAL = 0;
		private double _PL_MONTANTPERIODEPRECEDENTDEBITGESTION = 0;
		private double _PL_MONTANTPERIODEDEBITENCOURSGESTION = 0;
		private double _PL_MONTANTPERIODECREDITENCOURSGESTION = 0;
		private double _PL_MONTANTSOLDEFINALDEBITGESTION = 0;
		private double _PL_MONTANTPERIODEPRECEDENTDEBITBILAN = 0;
		private double _PL_MONTANTPERIODEDEBITENCOURSBILAN = 0;
		private double _PL_MONTANTPERIODECREDITENCOURSBILAN = 0;
		private double _PL_MONTANTSOLDEFINALDEBITBILAN = 0;
        private string _BI_DATEDEBUT ="";
        private string _BI_DATEFIN = "";
        private string _BI_TYPEBALANCE = "";


      


        #endregion

        #region ACCESSEURS

        public string AG_CODEAGENCE
		{
			get { return _AG_CODEAGENCE; }
			set {  _AG_CODEAGENCE = value; }
		}

		public string EN_CODEENTREPOT
		{
			get { return _EN_CODEENTREPOT; }
			set {  _EN_CODEENTREPOT = value; }
		}

		public string EX_EXERCICE
		{
			get { return _EX_EXERCICE; }
			set {  _EX_EXERCICE = value; }
		}

		public string PL_CODENUMCOMPTE
		{
			get { return _PL_CODENUMCOMPTE; }
			set {  _PL_CODENUMCOMPTE = value; }
		}

		public string MV_LIBELLEOPERATION
		{
			get { return _MV_LIBELLEOPERATION; }
			set {  _MV_LIBELLEOPERATION = value; }
		}

		public double PL_MONTANTPERIODEPRECEDENTDEBIT
		{
			get { return _PL_MONTANTPERIODEPRECEDENTDEBIT; }
			set {  _PL_MONTANTPERIODEPRECEDENTDEBIT = value; }
		}

		public double PL_MONTANTPERIODEPRECEDENTCREDIT
		{
			get { return _PL_MONTANTPERIODEPRECEDENTCREDIT; }
			set {  _PL_MONTANTPERIODEPRECEDENTCREDIT = value; }
		}

		public double PL_MONTANTPERIODEDEBITENCOURS
		{
			get { return _PL_MONTANTPERIODEDEBITENCOURS; }
			set {  _PL_MONTANTPERIODEDEBITENCOURS = value; }
		}

		public double PL_MONTANTPERIODECREDITENCOURS
		{
			get { return _PL_MONTANTPERIODECREDITENCOURS; }
			set {  _PL_MONTANTPERIODECREDITENCOURS = value; }
		}

		public double PL_MONTANTSOLDEFINALDEBIT
		{
			get { return _PL_MONTANTSOLDEFINALDEBIT; }
			set {  _PL_MONTANTSOLDEFINALDEBIT = value; }
		}

		public double PL_MONTANTSOLDEFINALCREDIT
		{
			get { return _PL_MONTANTSOLDEFINALCREDIT; }
			set {  _PL_MONTANTSOLDEFINALCREDIT = value; }
		}

		public double PL_MONTANTPERIODEPRECEDENTDEBITTOTAL
		{
			get { return _PL_MONTANTPERIODEPRECEDENTDEBITTOTAL; }
			set {  _PL_MONTANTPERIODEPRECEDENTDEBITTOTAL = value; }
		}

		public double PL_MONTANTPERIODEPRECEDENTCREDITTOTAL
		{
			get { return _PL_MONTANTPERIODEPRECEDENTCREDITTOTAL; }
			set {  _PL_MONTANTPERIODEPRECEDENTCREDITTOTAL = value; }
		}

		public double PL_MONTANTPERIODEDEBITENCOURSTOTAL
		{
			get { return _PL_MONTANTPERIODEDEBITENCOURSTOTAL; }
			set {  _PL_MONTANTPERIODEDEBITENCOURSTOTAL = value; }
		}

		public double PL_MONTANTPERIODECREDITENCOURSTOTAL
		{
			get { return _PL_MONTANTPERIODECREDITENCOURSTOTAL; }
			set {  _PL_MONTANTPERIODECREDITENCOURSTOTAL = value; }
		}

		public double PL_MONTANTSOLDEFINALDEBITTOTAL
		{
			get { return _PL_MONTANTSOLDEFINALDEBITTOTAL; }
			set {  _PL_MONTANTSOLDEFINALDEBITTOTAL = value; }
		}

		public double PL_MONTANTSOLDEFINALCREDITTOTAL
		{
			get { return _PL_MONTANTSOLDEFINALCREDITTOTAL; }
			set {  _PL_MONTANTSOLDEFINALCREDITTOTAL = value; }
		}

		public double PL_MONTANTPERIODEPRECEDENTDEBITGESTION
		{
			get { return _PL_MONTANTPERIODEPRECEDENTDEBITGESTION; }
			set {  _PL_MONTANTPERIODEPRECEDENTDEBITGESTION = value; }
		}

		public double PL_MONTANTPERIODEDEBITENCOURSGESTION
		{
			get { return _PL_MONTANTPERIODEDEBITENCOURSGESTION; }
			set {  _PL_MONTANTPERIODEDEBITENCOURSGESTION = value; }
		}

		public double PL_MONTANTPERIODECREDITENCOURSGESTION
		{
			get { return _PL_MONTANTPERIODECREDITENCOURSGESTION; }
			set {  _PL_MONTANTPERIODECREDITENCOURSGESTION = value; }
		}

		public double PL_MONTANTSOLDEFINALDEBITGESTION
		{
			get { return _PL_MONTANTSOLDEFINALDEBITGESTION; }
			set {  _PL_MONTANTSOLDEFINALDEBITGESTION = value; }
		}

		public double PL_MONTANTPERIODEPRECEDENTDEBITBILAN
		{
			get { return _PL_MONTANTPERIODEPRECEDENTDEBITBILAN; }
			set {  _PL_MONTANTPERIODEPRECEDENTDEBITBILAN = value; }
		}

		public double PL_MONTANTPERIODEDEBITENCOURSBILAN
		{
			get { return _PL_MONTANTPERIODEDEBITENCOURSBILAN; }
			set {  _PL_MONTANTPERIODEDEBITENCOURSBILAN = value; }
		}

		public double PL_MONTANTPERIODECREDITENCOURSBILAN
		{
			get { return _PL_MONTANTPERIODECREDITENCOURSBILAN; }
			set {  _PL_MONTANTPERIODECREDITENCOURSBILAN = value; }
		}

		public double PL_MONTANTSOLDEFINALDEBITBILAN
		{
			get { return _PL_MONTANTSOLDEFINALDEBITBILAN; }
			set {  _PL_MONTANTSOLDEFINALDEBITBILAN = value; }
		}

        public string BI_DATEDEBUT
        {
	        get { return _BI_DATEDEBUT; }
	        set { _BI_DATEDEBUT = value; }
        }

        public string BI_DATEFIN
        {
	        get { return _BI_DATEFIN; }
	        set { _BI_DATEFIN = value; }
        }

        public string BI_TYPEBALANCE
        {
	        get { return _BI_TYPEBALANCE; }
	        set { _BI_TYPEBALANCE = value; }
        }
    


        #endregion

        #region INSTANCIATEURS

        public clsBalanceinventaire(){}
		
		public clsBalanceinventaire(clsBalanceinventaire clsBalanceinventaire)
		{
			this.AG_CODEAGENCE = clsBalanceinventaire.AG_CODEAGENCE;
			this.EN_CODEENTREPOT = clsBalanceinventaire.EN_CODEENTREPOT;
			this.EX_EXERCICE = clsBalanceinventaire.EX_EXERCICE;
			this.PL_CODENUMCOMPTE = clsBalanceinventaire.PL_CODENUMCOMPTE;
			this.MV_LIBELLEOPERATION = clsBalanceinventaire.MV_LIBELLEOPERATION;
			this.PL_MONTANTPERIODEPRECEDENTDEBIT = clsBalanceinventaire.PL_MONTANTPERIODEPRECEDENTDEBIT;
			this.PL_MONTANTPERIODEPRECEDENTCREDIT = clsBalanceinventaire.PL_MONTANTPERIODEPRECEDENTCREDIT;
			this.PL_MONTANTPERIODEDEBITENCOURS = clsBalanceinventaire.PL_MONTANTPERIODEDEBITENCOURS;
			this.PL_MONTANTPERIODECREDITENCOURS = clsBalanceinventaire.PL_MONTANTPERIODECREDITENCOURS;
			this.PL_MONTANTSOLDEFINALDEBIT = clsBalanceinventaire.PL_MONTANTSOLDEFINALDEBIT;
			this.PL_MONTANTSOLDEFINALCREDIT = clsBalanceinventaire.PL_MONTANTSOLDEFINALCREDIT;
			this.PL_MONTANTPERIODEPRECEDENTDEBITTOTAL = clsBalanceinventaire.PL_MONTANTPERIODEPRECEDENTDEBITTOTAL;
			this.PL_MONTANTPERIODEPRECEDENTCREDITTOTAL = clsBalanceinventaire.PL_MONTANTPERIODEPRECEDENTCREDITTOTAL;
			this.PL_MONTANTPERIODEDEBITENCOURSTOTAL = clsBalanceinventaire.PL_MONTANTPERIODEDEBITENCOURSTOTAL;
			this.PL_MONTANTPERIODECREDITENCOURSTOTAL = clsBalanceinventaire.PL_MONTANTPERIODECREDITENCOURSTOTAL;
			this.PL_MONTANTSOLDEFINALDEBITTOTAL = clsBalanceinventaire.PL_MONTANTSOLDEFINALDEBITTOTAL;
			this.PL_MONTANTSOLDEFINALCREDITTOTAL = clsBalanceinventaire.PL_MONTANTSOLDEFINALCREDITTOTAL;
			this.PL_MONTANTPERIODEPRECEDENTDEBITGESTION = clsBalanceinventaire.PL_MONTANTPERIODEPRECEDENTDEBITGESTION;
			this.PL_MONTANTPERIODEDEBITENCOURSGESTION = clsBalanceinventaire.PL_MONTANTPERIODEDEBITENCOURSGESTION;
			this.PL_MONTANTPERIODECREDITENCOURSGESTION = clsBalanceinventaire.PL_MONTANTPERIODECREDITENCOURSGESTION;
			this.PL_MONTANTSOLDEFINALDEBITGESTION = clsBalanceinventaire.PL_MONTANTSOLDEFINALDEBITGESTION;
			this.PL_MONTANTPERIODEPRECEDENTDEBITBILAN = clsBalanceinventaire.PL_MONTANTPERIODEPRECEDENTDEBITBILAN;
			this.PL_MONTANTPERIODEDEBITENCOURSBILAN = clsBalanceinventaire.PL_MONTANTPERIODEDEBITENCOURSBILAN;
			this.PL_MONTANTPERIODECREDITENCOURSBILAN = clsBalanceinventaire.PL_MONTANTPERIODECREDITENCOURSBILAN;
			this.PL_MONTANTSOLDEFINALDEBITBILAN = clsBalanceinventaire.PL_MONTANTSOLDEFINALDEBITBILAN;
	        this.BI_DATEDEBUT = clsBalanceinventaire.BI_DATEDEBUT;
            this.BI_DATEFIN = clsBalanceinventaire.BI_DATEFIN;
            this.BI_TYPEBALANCE = clsBalanceinventaire.BI_TYPEBALANCE;





        }

		#endregion

	}
}
